name: anyscale-academy
channels:
  - conda-forge
  - pyviz
dependencies:
  - python=3.7.7
  - pip
  - pandas
  - requests
  - pytorch
  - torchvision
  - tensorboard
  - tensorflow
  - keras
  - scikit-learn
  - holoviews
  - bokeh
  - ipywidgets
  - psutil
  - jupyterlab
  - jupyter-server-proxy
  - beautifulsoup4
  - lxml
  - setproctitle
  - pytz
  - nodejs
  - pip:
    - ray[all]==0.8.7
    - atoma
    - box2d-py

