name: anyscale-academy
channels:
  - conda-forge
  - pyviz
dependencies:
  - python=3.7
  - pip
  - gym >= 0.17.2
  - numpy >= 1.18.5
  - pandas
  - requests
  - pytorch
  - torchvision
  - tqdm >= 4.37.0
  - keras
  - scikit-learn
  - holoviews
  - bokeh
  - ipywidgets
  - psutil
  - jupyterlab
  - jupyter-server-proxy
  - beautifulsoup4
  - lxml
  - pytz
  - nodejs
  - pip:
    - ray[all]==0.8.7
    - tensorboard >= 2.3.0
    - tensorflow >= 2.3.0
    - atoma
    - box2d-py

